name=SparkFun ADS1219 Arduino Library
version=2.0.0
author=SparkFun Electronics <techsupport@sparkfun.com>
maintainer=SparkFun Electronics
sentence=An Arduino library for the ADS1219 24-Bit 4-Channel ADC from TI
paragraph=An Arduino library for the ADC found on the <a href="https://www.sparkfun.com/products/23455">SparkFun Qwiic 24-Bit 4-Channel ADC - ADS1219</a>. NOTE: Version 2.0 and above of this library uses the SparkFun Toolkit, and device methods return a sfTkError_t (ksfTkErrOk on success). The class SfeADS1219ArdI2C retains the version 1.x boolean behavior.
category=Signal Input/Output
url=https://github.com/sparkfun/SparkFun_ADS1219_Arduino_Library
architectures=*
depends=SparkFun Toolkit (>=1.2.0)